-- Universal Music Group Music Collection Lab Setup
-- Creates database, schema, tables, and stages for storing Discogs collection data and artwork

-- Step 1: Create database and schema
CREATE DATABASE IF NOT EXISTS UNIVERSAL_MUSIC_GROUP_MUSIC_COLLECTION;
USE DATABASE UNIVERSAL_MUSIC_GROUP_MUSIC_COLLECTION;
CREATE SCHEMA IF NOT EXISTS COLLECTION_DATA;
USE SCHEMA COLLECTION_DATA;

-- Step 2: Create external stage for storing artwork images
CREATE OR REPLACE STAGE ARTWORK_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for storing Discogs album artwork and images';

-- Step 3: Create file format for JSON data
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    COMMENT = 'File format for JSON data from Discogs API';

-- Step 4: Create collections table for basic collection info
CREATE OR REPLACE TABLE COLLECTIONS (
    COLLECTION_ID VARCHAR(50) PRIMARY KEY,
    USER_ID VARCHAR(50),
    USERNAME VARCHAR(100),
    COLLECTION_NAME VARCHAR(200),
    TOTAL_ITEMS INTEGER,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Step 5: Create releases table for individual album/release data
CREATE OR REPLACE TABLE RELEASES (
    RELEASE_ID VARCHAR(50) PRIMARY KEY,
    COLLECTION_ID VARCHAR(50),
    BASIC_INFORMATION VARIANT,
    DISCOGS_ID INTEGER,
    TITLE VARCHAR(500),
    ARTIST VARCHAR(500),
    YEAR INTEGER,
    LABEL VARCHAR(500),
    CATNO VARCHAR(100),
    FORMAT VARCHAR(200),
    GENRES ARRAY,
    STYLES ARRAY,
    COUNTRY VARCHAR(100),
    DATE_ADDED TIMESTAMP_NTZ,
    INSTANCE_ID INTEGER,
    FOLDER_ID INTEGER,
    RATING INTEGER,
    NOTES VARCHAR(2000),
    CONDITION VARCHAR(100),
    SLEEVE_CONDITION VARCHAR(100),
    MARKETPLACE_STATS VARIANT,
    ARTWORK_URLS ARRAY,
    LOCAL_ARTWORK_PATHS ARRAY,
    RAW_DATA VARIANT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTIONS(COLLECTION_ID)
);

-- Step 6: Create artists table for normalized artist data
CREATE OR REPLACE TABLE ARTISTS (
    ARTIST_ID VARCHAR(50) PRIMARY KEY,
    ARTIST_NAME VARCHAR(500),
    REAL_NAME VARCHAR(500),
    PROFILE TEXT,
    DISCOGS_ARTIST_ID INTEGER,
    IMAGES ARRAY,
    URLS ARRAY,
    MEMBERS ARRAY,
    GROUPS ARRAY,
    ALIASES ARRAY,
    RAW_DATA VARIANT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Step 7: Create labels table for record label information
CREATE OR REPLACE TABLE LABELS (
    LABEL_ID VARCHAR(50) PRIMARY KEY,
    LABEL_NAME VARCHAR(500),
    CONTACT_INFO VARCHAR(1000),
    PROFILE TEXT,
    DISCOGS_LABEL_ID INTEGER,
    IMAGES ARRAY,
    URLS ARRAY,
    PARENT_LABEL VARCHAR(500),
    SUBLABELS ARRAY,
    RAW_DATA VARIANT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Step 8: Create artwork table for image metadata
CREATE OR REPLACE TABLE ARTWORK (
    ARTWORK_ID VARCHAR(50) PRIMARY KEY,
    RELEASE_ID VARCHAR(50),
    IMAGE_TYPE VARCHAR(50), -- 'primary', 'secondary', 'cover', 'back', etc.
    ORIGINAL_URL VARCHAR(1000),
    LOCAL_FILE_PATH VARCHAR(500),
    STAGE_FILE_PATH VARCHAR(500),
    FILE_SIZE INTEGER,
    IMAGE_WIDTH INTEGER,
    IMAGE_HEIGHT INTEGER,
    FILE_FORMAT VARCHAR(20),
    DOWNLOAD_DATE TIMESTAMP_NTZ,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (RELEASE_ID) REFERENCES RELEASES(RELEASE_ID)
);

-- Step 9: Create master releases table for release groups
CREATE OR REPLACE TABLE MASTER_RELEASES (
    MASTER_ID VARCHAR(50) PRIMARY KEY,
    DISCOGS_MASTER_ID INTEGER,
    TITLE VARCHAR(500),
    MAIN_RELEASE_ID VARCHAR(50),
    YEAR INTEGER,
    GENRES ARRAY,
    STYLES ARRAY,
    IMAGES ARRAY,
    VIDEOS ARRAY,
    ARTISTS ARRAY,
    VERSIONS_COUNT INTEGER,
    LOWEST_PRICE DECIMAL(10,2),
    RAW_DATA VARIANT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Step 10: Create collection statistics view
CREATE OR REPLACE VIEW COLLECTION_STATS AS
SELECT 
    c.COLLECTION_ID,
    c.USERNAME,
    c.TOTAL_ITEMS,
    COUNT(r.RELEASE_ID) as DOWNLOADED_ITEMS,
    COUNT(DISTINCT r.ARTIST) as UNIQUE_ARTISTS,
    COUNT(DISTINCT r.LABEL) as UNIQUE_LABELS,
    COUNT(DISTINCT r.YEAR) as YEARS_SPAN,
    MIN(r.YEAR) as EARLIEST_YEAR,
    MAX(r.YEAR) as LATEST_YEAR,
    COUNT(DISTINCT r.COUNTRY) as COUNTRIES,
    ROUND(AVG(r.RATING), 2) as AVG_RATING,
    COUNT(a.ARTWORK_ID) as ARTWORK_COUNT,
    SUM(a.FILE_SIZE) as TOTAL_ARTWORK_SIZE_BYTES
FROM COLLECTIONS c
LEFT JOIN RELEASES r ON c.COLLECTION_ID = r.COLLECTION_ID
LEFT JOIN ARTWORK a ON r.RELEASE_ID = a.RELEASE_ID
GROUP BY c.COLLECTION_ID, c.USERNAME, c.TOTAL_ITEMS;

-- Step 11: Create genre analysis view
CREATE OR REPLACE VIEW GENRE_ANALYSIS AS
SELECT 
    genre.value::STRING as GENRE,
    COUNT(*) as RELEASE_COUNT,
    COUNT(DISTINCT r.ARTIST) as ARTIST_COUNT,
    ROUND(AVG(r.YEAR), 0) as AVG_YEAR,
    ROUND(AVG(r.RATING), 2) as AVG_RATING
FROM RELEASES r,
LATERAL FLATTEN(input => r.GENRES) genre
WHERE r.GENRES IS NOT NULL
GROUP BY genre.value::STRING
ORDER BY RELEASE_COUNT DESC;

-- Step 12: Create decade analysis view
CREATE OR REPLACE VIEW DECADE_ANALYSIS AS
SELECT 
    FLOOR(r.YEAR / 10) * 10 as DECADE,
    COUNT(*) as RELEASE_COUNT,
    COUNT(DISTINCT r.ARTIST) as ARTIST_COUNT,
    ROUND(AVG(r.RATING), 2) as AVG_RATING,
    ARRAY_AGG(DISTINCT genre.value::STRING) as GENRES
FROM RELEASES r,
LATERAL FLATTEN(input => r.GENRES) genre
WHERE r.YEAR IS NOT NULL AND r.GENRES IS NOT NULL
GROUP BY FLOOR(r.YEAR / 10) * 10
ORDER BY DECADE;

-- Step 13: Create search function for collection
CREATE OR REPLACE FUNCTION SEARCH_COLLECTION(SEARCH_TERM VARCHAR)
RETURNS TABLE (
    RELEASE_ID VARCHAR(50),
    TITLE VARCHAR(500),
    ARTIST VARCHAR(500),
    YEAR INTEGER,
    LABEL VARCHAR(500),
    RELEVANCE_SCORE FLOAT
)
AS
$$
SELECT 
    r.RELEASE_ID,
    r.TITLE,
    r.ARTIST,
    r.YEAR,
    r.LABEL,
    -- Simple relevance scoring based on text matches
    (
        CASE WHEN UPPER(r.TITLE) LIKE UPPER('%' || SEARCH_TERM || '%') THEN 3.0 ELSE 0.0 END +
        CASE WHEN UPPER(r.ARTIST) LIKE UPPER('%' || SEARCH_TERM || '%') THEN 2.0 ELSE 0.0 END +
        CASE WHEN UPPER(r.LABEL) LIKE UPPER('%' || SEARCH_TERM || '%') THEN 1.0 ELSE 0.0 END +
        CASE WHEN ARRAY_CONTAINS(UPPER(SEARCH_TERM)::VARIANT, 
                  ARRAY_CONSTRUCT_COMPACT(
                      ARRAY_MAP(x -> UPPER(x::STRING), r.GENRES)
                  )) THEN 1.5 ELSE 0.0 END
    ) as RELEVANCE_SCORE
FROM RELEASES r
WHERE RELEVANCE_SCORE > 0
ORDER BY RELEVANCE_SCORE DESC, r.ARTIST, r.YEAR
$$;

-- Step 14: Grant necessary permissions (adjust as needed for your environment)
-- GRANT USAGE ON DATABASE DISCOGS_COLLECTION TO ROLE PUBLIC;
-- GRANT USAGE ON SCHEMA COLLECTION_DATA TO ROLE PUBLIC;
-- GRANT SELECT ON ALL TABLES IN SCHEMA COLLECTION_DATA TO ROLE PUBLIC;
-- GRANT SELECT ON ALL VIEWS IN SCHEMA COLLECTION_DATA TO ROLE PUBLIC;

-- Step 15: Create procedure to update last_updated timestamps
CREATE OR REPLACE PROCEDURE UPDATE_LAST_MODIFIED(TABLE_NAME VARCHAR, RECORD_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    CASE 
        WHEN TABLE_NAME = 'COLLECTIONS' THEN
            UPDATE COLLECTIONS SET LAST_UPDATED = CURRENT_TIMESTAMP() WHERE COLLECTION_ID = RECORD_ID;
        WHEN TABLE_NAME = 'RELEASES' THEN
            UPDATE RELEASES SET LAST_UPDATED = CURRENT_TIMESTAMP() WHERE RELEASE_ID = RECORD_ID;
        WHEN TABLE_NAME = 'ARTISTS' THEN
            UPDATE ARTISTS SET LAST_UPDATED = CURRENT_TIMESTAMP() WHERE ARTIST_ID = RECORD_ID;
        WHEN TABLE_NAME = 'LABELS' THEN
            UPDATE LABELS SET LAST_UPDATED = CURRENT_TIMESTAMP() WHERE LABEL_ID = RECORD_ID;
        WHEN TABLE_NAME = 'MASTER_RELEASES' THEN
            UPDATE MASTER_RELEASES SET LAST_UPDATED = CURRENT_TIMESTAMP() WHERE MASTER_ID = RECORD_ID;
    END CASE;
    RETURN 'Updated ' || TABLE_NAME || ' record ' || RECORD_ID;
END;
$$;

-- Confirmation message
SELECT 'Discogs Collection database setup completed successfully!' as SETUP_STATUS;