-- Snowflake setup for Discogs Collection (SiS)
-- Creates roles, warehouses, database, schema, stages, and tables

-- Roles
CREATE ROLE IF NOT EXISTS DISCOGS_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS DISCOGS_READER_ROLE;

-- Grants
GRANT ROLE DISCOGS_ADMIN_ROLE TO ROLE SYSADMIN;
GRANT ROLE DISCOGS_READER_ROLE TO ROLE DISCOGS_ADMIN_ROLE;

-- Warehouse (adjust size as needed)
CREATE WAREHOUSE IF NOT EXISTS DISCOGS_WH WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database and schema
CREATE DATABASE IF NOT EXISTS DISCOGS_DB;
CREATE SCHEMA IF NOT EXISTS DISCOGS_DB.COLLECTION_DATA;

-- Grants for schema
GRANT USAGE ON DATABASE DISCOGS_DB TO ROLE DISCOGS_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DISCOGS_DB.COLLECTION_DATA TO ROLE DISCOGS_ADMIN_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA DISCOGS_DB.COLLECTION_DATA TO ROLE DISCOGS_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE DISCOGS_WH TO ROLE DISCOGS_ADMIN_ROLE;

-- Reader grants
GRANT USAGE ON DATABASE DISCOGS_DB TO ROLE DISCOGS_READER_ROLE;
GRANT USAGE ON SCHEMA DISCOGS_DB.COLLECTION_DATA TO ROLE DISCOGS_READER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DISCOGS_DB.COLLECTION_DATA TO ROLE DISCOGS_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DISCOGS_DB.COLLECTION_DATA TO ROLE DISCOGS_READER_ROLE;

-- External stage for artwork (internal stage can be used as well)
CREATE STAGE IF NOT EXISTS DISCOGS_DB.COLLECTION_DATA.ARTWORK_STAGE;

-- Tables
CREATE TABLE IF NOT EXISTS DISCOGS_DB.COLLECTION_DATA.RELEASES (
  RELEASE_ID INTEGER AUTOINCREMENT,
  DISCOGS_ID INTEGER,
  TITLE STRING,
  ARTIST STRING,
  LABEL STRING,
  CATNO STRING,
  FORMAT STRING,
  YEAR INTEGER,
  COUNTRY STRING,
  RATING INTEGER,
  CONDITION STRING,
  SLEEVE_CONDITION STRING,
  DATE_ADDED TIMESTAMP,
  GENRES ARRAY,
  STYLES ARRAY,
  PRODUCERS ARRAY,
  COPIES_COUNT INTEGER,
  INSTANCE_IDS ARRAY,
  ARTWORK_FILES ARRAY,
  COMMUNITY_HAVE_COUNT INTEGER,
  COMMUNITY_WANT_COUNT INTEGER,
  COMMUNITY_RATING_COUNT INTEGER,
  COMMUNITY_AVERAGE_RATING FLOAT,
  STATS_LAST_UPDATED TIMESTAMP,
  PRIMARY KEY (RELEASE_ID)
);

CREATE TABLE IF NOT EXISTS DISCOGS_DB.COLLECTION_DATA.ARTWORK (
  ARTWORK_ID INTEGER AUTOINCREMENT,
  RELEASE_ID INTEGER,
  IMAGE_TYPE STRING,
  ORIGINAL_URL STRING,
  STORAGE_PATH STRING,
  THUMBNAIL_PATH STRING,
  FILE_SIZE NUMBER,
  IMAGE_WIDTH NUMBER,
  IMAGE_HEIGHT NUMBER,
  PRIMARY KEY (ARTWORK_ID)
);

CREATE TABLE IF NOT EXISTS DISCOGS_DB.COLLECTION_DATA.MARKETPLACE_STATS_DIM (
  DISCOGS_RELEASE_ID INTEGER PRIMARY KEY,
  LAST_SOLD_DATE DATE,
  LOW_SOLD_PRICE NUMBER(10,2),
  HIGH_SOLD_PRICE NUMBER(10,2),
  CURRENCY STRING,
  AS_OF TIMESTAMP,
  NOTES STRING
);

CREATE TABLE IF NOT EXISTS DISCOGS_DB.COLLECTION_DATA.RELEASE_PRICES (
  DISCOGS_RELEASE_ID INTEGER,
  NUM_FOR_SALE INTEGER,
  LOWEST_PRICE NUMBER(10,2),
  CURRENCY STRING,
  LAST_SEEN TIMESTAMP
);

-- Helpful view examples
CREATE OR REPLACE VIEW DISCOGS_DB.COLLECTION_DATA.V_RELEASES_SIMPLE AS
SELECT 
  RELEASE_ID, DISCOGS_ID, TITLE, ARTIST, LABEL, YEAR, COUNTRY, GENRES, STYLES,
  COMMUNITY_HAVE_COUNT, COMMUNITY_WANT_COUNT, COMMUNITY_AVERAGE_RATING, COMMUNITY_RATING_COUNT
FROM DISCOGS_DB.COLLECTION_DATA.RELEASES;
